[project]
name = "gemini-sim-portfolio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dataclasses>=0.8",
    "pandas>=2.2.3",
    "tabulate>=0.9.0",
    "typing>=3.10.0.0",
]
